### ISSUE TITLE
Data not displaying any more

### ISSUE THREAD

**Issue by sublimeshutter** [peted-davis/WeatherFlow_PiConsole#102]
The 4 panes Temp, Wind Speed, Rainfall and Barometer are not displaying data from my tempest. I have tried updating the WeatherFlow software and the Pi software. Have restarted several times. checked the API as well.

Any suggestions on what to try next?

Cheers,

**Comment by peted-davis** [comment]
What is your station ID?

**Comment by sublimeshutter** [comment]
ST-00021197



From: Pete Davis ***@***.***>
Date: Friday, 14 April 2023 at 17:26
To: peted-davis/WeatherFlow_PiConsole ***@***.***>
Cc: earl ***@***.***>, Author ***@***.***>
Subject: Re: [peted-davis/WeatherFlow_PiConsole] Data not displaying any more (Issue #102)

What is your station ID?

**Comment by sublimeshutter** [comment]
Apologies

https://tempestwx.com/station/35430/grid



From: Pete Davis ***@***.***>
Date: Friday, 14 April 2023 at 17:30
To: peted-davis/WeatherFlow_PiConsole ***@***.***>
Cc: earl ***@***.***>, Author ***@***.***>
Subject: Re: [peted-davis/WeatherFlow_PiConsole] Data not displaying any more (Issue #102)

That's your Tempest serial number. I need to know the station ID. It's the number that appears in the web URL to your station page. E.g: https://tempestwx.com/station/33581/

**Comment by sublimeshutter** [comment]
Here you go. Thanks very much for investigating!


Last login: Wed Apr  5 08:26:02 on console

***@***.*** ~ % ssh ***@***.******@***.***>

***@***.******@***.***'s> password:

Linux tempest 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l



The programs included with the Debian GNU/Linux system are free software;

the exact distribution terms for each program are described in the

individual files in /usr/share/doc/*/copyright.



Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent

permitted by applicable law.

Last login: Wed Apr  5 16:55:29 2023

***@***.***:~ $ ls

Bookshelf  Documents  Music     Public     Videos

Desktop    Downloads  Pictures  Templates  wfpiconsole

***@***.***:~ $ cd wfpiconsole

***@***.***:~/wfpiconsole $ ls

atlas  kvlang   main.py    service          wfpiconsole.kv       wfpiconsole.sh

fonts  lib      panels     user             wfpiconsole.log

icons  LICENSE  README.md  wfpiconsole.ini  wfpiconsole.service

***@***.***:~/wfpiconsole $ sudo nano wfpiconsole.ini



































































































































  GNU nano 3.2                                                                                                                wfpiconsole.ini



[Keys]

WeatherFlow = 4ceaa9e3-262b-4747-8dd1-f69dff231d21

CheckWX = 15ab9acd5f664c219a4983bf22



[Station]

StationID = 35430

TempestID = 109013

SkyID =

OutAirID =

InAirID =

TempestHeight = 4.0

SkyHeight =

OutAirHeight =

Latitude = -37.98451

Longitude = 145.04905

Elevation = 23.21691131591797

Timezone = Australia/Melbourne

Name = Ausmerican



[Units]

Temp = c

Pressure = mb

Wind = kph

Direction = cardinal

Precip = mm

Distance = km

Other = metric



[Display]

TimeFormat = 24 hr

DateFormat = Mon, 01 Jan 0000

LightningPanel = 1

IndoorTemp = 1

Cursor = 1

Border = 1

Fullscreen = 1

Width = 800

Height = 480



[FeelsLike]

ExtremelyCold = -4

FreezingCold = 0

VeryCold = 4

Cold = 9

Mild = 14

Warm = 18

Hot = 23

VeryHot = 28



[PrimaryPanels]

PanelOne = Forecast

PanelTwo = Temperature

PanelThree = WindSpeed

PanelFour = SunriseSunset

PanelFive = Rainfall

PanelSix = Barometer



[SecondaryPanels]

PanelOne = Sager

PanelTwo =

PanelThree =

PanelFour = MoonPhase

PanelFive =

PanelSix = Lightning



[System]

BarometerMax = 1050

BarometerMin = 950

SagerInterval = 6

Timeout = 20

Hardware = Pi3

Version = v23.3.1





















^G Get Help      ^O Write Out     ^W Where Is      ^K Cut Text      ^J Justify       ^C Cur Pos       M-U Undo         M-A Mark Text    M-] To Bracket   M-Q Previous     ^B Back          ^◀ Prev Word     ^A Home          ^P Prev Line     M-- Scroll Up

^X Exit          ^R Read File     ^\ Replace       ^U Uncut Text    ^T To Spell      ^_ Go To Line    M-E Redo         M-6 Copy Text    ^Q Where Was     M-W Next         ^F Forward       ^▶ Next Word     ^E End           ^N Next Line     M-+ Scroll Down


From: Pete Davis ***@***.***>
Date: Friday, 14 April 2023 at 17:36
To: peted-davis/WeatherFlow_PiConsole ***@***.***>
Cc: earl ***@***.***>, Author ***@***.***>
Subject: Re: [peted-davis/WeatherFlow_PiConsole] Data not displaying any more (Issue #102)

Thanks! I can't see any issues there (except your battery voltage is relatively low). Are any errors printed to the terminal when you run the console? Can you share the complete contents of your wfpiconsole.ini file? That way I can run your station and investigate further

**Comment by peted-davis** [comment]
No problem! I have no issues running your station here - everything is displaying fine. Have you checked the network connection on your Pi? 

![unnamed (1)](https://user-images.githubusercontent.com/10545710/231979846-e67a559e-519d-4be0-b246-72752cc2b584.jpg)

**Comment by sublimeshutter** [comment]
I can ssh into it from my mac so I assume that means it’s on my network. And looking at my router page it shows the pi connected…

I just went into Raspi-Config and re-entered the wifi and password but still no joy.

Sorry to have bothered you. I am missing something here

From: Pete Davis ***@***.***>
Date: Friday, 14 April 2023 at 17:50
To: peted-davis/WeatherFlow_PiConsole ***@***.***>
Cc: earl ***@***.***>, Author ***@***.***>
Subject: Re: [peted-davis/WeatherFlow_PiConsole] Data not displaying any more (Issue #102)

No problem! I have no issues running your station here - everything is displaying fine. Have you checked the network connection on your Pi?

[unnamed (1)]<https://user-images.githubusercontent.com/10545710/231979846-e67a559e-519d-4be0-b246-72752cc2b584.jpg>

**Comment by peted-davis** [comment]
Can you ping external websites from your pi? Try running `ping google.co.uk`
