### ISSUE TITLE
Cant get the console to run and open

### ISSUE THREAD

**Issue by tristrand** [peted-davis/WeatherFlow_PiConsole#103]
**Describe the bug**
everytime i try to run the console this is all I get. I even tried the restart the raspberry pi

**To Reproduce**
1)open terminal 
2)run wfpiconsole start
![wpCapture](https://user-images.githubusercontent.com/101128624/235272276-e0f4bc65-d3e7-4cee-a437-c31de5b24861.PNG)

**Screenshots**

**Hardware/OS/Version (please complete the following information):**
 - OS: Raspberry Pi OS 32-bit
 - Hardware: Pi4
 - Console Version: 22.3.1

**Additional context**
trisrand@raspberrypi:~ $ wfpiconsole start
[INFO   ] [Logger      ] Record log in /home/trisrand/.kivy/logs/kivy_23-04-28_1.txt
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/home/trisrand/.local/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.2 (default, Mar 12 2021, 04:06:34)
[GCC 10.2.1 20210110]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Config      ] Verifying station details
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'2.1 Mesa 20.3.5'>
[INFO   ] [GL          ] OpenGL vendor <b'Broadcom'>
[INFO   ] [GL          ] OpenGL renderer <b'V3D 4.2'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <4096>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2(['text_pango'] ignored)
[INFO   ] [GL          ] NPOT texture support is available
Unable to connect to X server
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [HIDInput    ] Read event from </dev/input/event2>
[INFO   ] [Websocket   ] 2023-04-28 19:11:35 - Opening connection
[INFO   ] [Base        ] Start application main loop
[INFO   ] [HIDMotionEvent] using <generic ft5x06 (00)>
[INFO   ] [HIDMotionEvent] <generic ft5x06 (00)> range ABS X position is 0 - 799
[INFO   ] [HIDMotionEvent] <generic ft5x06 (00)> range ABS Y position is 0 - 479
[INFO   ] [HIDMotionEvent] <generic ft5x06 (00)> range position X is 0 - 799
[INFO   ] [HIDMotionEvent] <generic ft5x06 (00)> range position Y is 0 - 479
[INFO   ] [Websocket   ] 2023-04-28 19:11:36 - Connection open

**Comment by peted-davis** [comment]
Are you trying to connect to the pi using ssh? If so, use VNC instead
