### ISSUE TITLE
Not a bug - question

### ISSUE THREAD

**Issue by adamsfour** [peted-davis/WeatherFlow_PiConsole#104]
My display indicates an update is available. I have mine setup to auto start each time I stop the program or reboot. Can I simply run update ( from a ssh session) and then reboot or do I need to turn off auto start, stop program, upgrade, turn auto start back on, and restart  Thanks

**Comment by peted-davis** [comment]
Yes, you can run the update and then reboot with no problems. 

Or, to avoid rebooting run `wfpiconsole autostart-disable` (this will stop the current instance of the console too), then update with `wfpiconsole update`, and then enable autostart again with `wfpiconsole autostart-enable` (which will also start the console without a reboot required)
