### ISSUE TITLE
Barometric pressure trend shows positive value when pressure is slowly falling

### ISSUE THREAD

**Issue by karlkec** [peted-davis/WeatherFlow_PiConsole#110]
**Describe the bug**
When the barometric pressure trend is slowly falling,  the pressure change shows as a positive number.

**To Reproduce**
1. Set pressure units to inHg
2. Wait for barometric pressure to be slowly falling
3. Over the period of an hour or two, manually record SLP pressure and numeric Trend value from the console, to confirm slowly falling SLP.
4. Note that the numeric trend value shows a positive number.

I think under these conditions the trend value should be negative.

**Hardware/OS/Version:**
 - OS: Raspberry Pi OS Buster 32-bit
 - Hardware: Pi 3 model B, with 
 - Console Version: v23.5.beta, as reported after pressing the Menu button on the console, however the version in config.py is v23.3.1. (Note that I switched to the beta branch, then back to stable)
  
**Suggested Resolution**
In lib/observationFormat.py line 258, I'm guessing the round() and subsequent abs() functions are used to prevent a negative sign preceeding a zero value. In this case, the inHg/hr pressure trend value is displayed to three digits. So I think the second argument to round() should be changed from 1 to 3, to match the number of digits displayed.
Similarly, in line 263, I think the second argument to round() should be 2, for mmHg/hr.

**Comment by peted-davis** [comment]
Good spot - I think the rounding issue you identified is the culprit. I will get this fixed up in the next version

**Comment by peted-davis** [comment]
This is now fixed in v22.10.1
