### ISSUE TITLE
New Feature Ideas

### ISSUE THREAD

**Issue by pgeremia** [peted-davis/WeatherFlow_PiConsole#111]
1. Add display themes.  For example LIGHT theme.
2. New LARGE temperature panel so you can see the outside temp from across the room.

Thank you for this awesome system.  I had it very quickly up and running and love it!!

**Comment by crwdplezer** [comment]
ADD RADAR!

**Comment by peted-davis** [comment]
The ability to select the number of display panels (1, 4, or 6) has been added to v23.10.1. This will allow you have to have a large temperature panel
