### ISSUE TITLE
WFPIconsole does not install on debian bookworm

### ISSUE THREAD

**Issue by pjmpessers** [peted-davis/WeatherFlow_PiConsole#112]
**Describe the bug**
Try to install wfpiconsole on debrian bookworm

**To Reproduce**
1. Install with command (curl -sSL https://peted-davis.github.io/wfpiconsole | bash)

Getting error: 
[i] Installing WeatherFlow PiConsole Python modules...
  [✗] Updating Python package manager
  Error: Unable to update Python package manager: pip

 error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Screenshots**

**Hardware/OS/Version (please complete the following information):**
 - debian bookworm
 - PI4
 

**Additional context**

**Comment by peted-davis** [comment]
Thanks for the bug report. This is a known issue related to a change in how Python package managers work: https://peps.python.org/pep-0668/. I will update the installer to become compatible with this change

**Comment by pjmpessers** [comment]
Thank you Pete.
Great to hear. 🙏🏻👍🏻
