### ISSUE TITLE
Pi 3 B+ and access to the on screen menu

### ISSUE THREAD

**Issue by crwdplezer** [peted-davis/WeatherFlow_PiConsole#114]
I have tried everything to get access to the onscreen menu. I have used VNC....but the weird thing is...I don't see the console on my computer when using VNC. I see the PI desktop all while the console is showing on the separate monitor. Mouse works for the desktop if I shut down WFPICONSOLE but no matter what I do I cannot get mouse access to the console or even see it using VNC. Wonder if it has to do with using Legacy OS on pi3. Any help is appreciated

**Comment by peted-davis** [comment]
This is a known hardware related Pi3 issue. The console cannot be viewed via VNC. If this is critical for your use, I would suggest upgrading to a Pi4
