### ISSUE TITLE
Lightning not reverting back to barometer

### ISSUE THREAD

**Issue by MABeatty1978** [peted-davis/WeatherFlow_PiConsole#115]
**Describe the bug**
When there is a lighting strike, the "barometer" box in the lower left automatically switches over to a lighting strike display.  This works fine, but the display never switches back to barometer.  I don't know if this is a bug or intended behavior, but I think I remember it automatically reverting back to barometer at some point?

**Hardware/OS/Version (please complete the following information):**
 - OS: Raspberry Pi OS Bullseye
 - Hardware: Pi3
 - Console Version: 23.3.1]

**Comment by peted-davis** [comment]
This is intended behaviour. The idea is that by permanently switching to the lightning panel, the user will be aware that lightning has been detected, even if they weren't present when the lightning struck. If the console were to switch back automatically, users could be unaware that lightning was detected
