### ISSUE TITLE
Issue with rain totals - different values than what appears on app 

### ISSUE THREAD

**Issue by tw15egan** [peted-davis/WeatherFlow_PiConsole#118]
Hey there! First off thanks for all your work on this app, I love it.

**Describe the bug**
I noticed yesterday that the totals in the display differ from what is displayed on my app.

**To Reproduce**
View screen

**Screenshots**
Display:
![IMG_0607](https://github.com/peted-davis/WeatherFlow_PiConsole/assets/11928039/6aa64c43-61ec-43be-b7cc-a1026d3fcfe8)

Yesterday
![IMG_0610](https://github.com/peted-davis/WeatherFlow_PiConsole/assets/11928039/0b3e3adb-26aa-46d4-b929-b1db2d61510c)

Month
![IMG_0609](https://github.com/peted-davis/WeatherFlow_PiConsole/assets/11928039/0de188f3-bcfc-4225-98e5-d51dd436241b)

Year
![IMG_0608 2](https://github.com/peted-davis/WeatherFlow_PiConsole/assets/11928039/e543745f-09c9-4fd2-b5cf-f2bf1a10d120)

**Hardware/OS/Version (please complete the following information):**
 - OS: Debian Buster / Bullseye (two devices)
 - Hardware: pi3 + pi4
 - Console Version: Latest, just tried updating

**Additional context**
The only thing I can think of is that I had turned off the "nearcast data" for a few days to see if I got wildly different readings, but I ended up turning it back on. I did this about 2 weeks ago and turned it back on within a few days (All would have been within the month of September, but year totals are still skewed). Is there any way to "refresh" the data on the display with what is stored on in the app?

Thanks again for your help!

**Comment by peted-davis** [comment]
This will be a NearCast rain issue. The console does not display NearCast values, so if you have NearCast enabled in the app, then the rain values will differ compared to the console

**Comment by tw15egan** [comment]
Excellent, thanks for the clarification 👍🏻
