### ISSUE TITLE
wfpiconsolewfpiconsole.log in ~/

### ISSUE THREAD

**Issue by MABeatty1978** [peted-davis/WeatherFlow_PiConsole#127]
**Describe the bug**
The log file is being written to ~/ and has the name wfpiconsolewfpiconsole.log

I'm guessing this the result of a bug in wfpiconsole.service as the StandardOutput and StandardError variables are missing the "/" in what is supposed to be wfpiconsole/wfpiconsole.log

**Screenshots**

<img width="677" alt="Screenshot 2023-10-30 at 1 30 45 PM" src="https://github.com/peted-davis/WeatherFlow_PiConsole/assets/23058027/fbd019c1-21af-4954-b41e-30ce43ba9805">

**Comment by peted-davis** [comment]
Thanks for spotting this. I can confirm this is a bug and a / is missing. I'll get this fixed up

**Comment by peted-davis** [comment]
This should now be fixed in v23.11.1
