### ISSUE TITLE
Thermometer icon showing up

### ISSUE THREAD

**Issue by MABeatty1978** [peted-davis/WeatherFlow_PiConsole#128]
**Describe the bug**
This seems to be random and I cannot figure out how to replicate it, it just shows up for a while and then goes away.  See circled icon in the screenshot

**To Reproduce**

**Screenshots**
If applicable, add 
![PXL_20231030_184241818](https://github.com/peted-davis/WeatherFlow_PiConsole/assets/23058027/6ef42cd2-48a0-43db-96aa-74051ec43934)
screenshots to help explain your problem.

**Hardware/OS/Version (please complete the following information):**
 - OS: Bookworm
 - Hardware: Pi3
 - Console Version: Most recent upgrade

**Comment by peted-davis** [comment]
That's a Raspberry Pi thing showing that your Pi is getting too hot and is overheating. The OS will be throttling the CPU to keep the temperatures in check. You'll probably want to consider improving the airflow to the Pi

**Comment by MABeatty1978** [comment]
Ooooffff.... I knew that too. Sorry

**Comment by peted-davis** [comment]
No problem! It is confusing when seen on a weather display 😂
