### ISSUE TITLE
Rainfall value differs from Tempest app on iphone

### ISSUE THREAD

**Issue by geewizard1** [peted-davis/WeatherFlow_PiConsole#132]
Rainfall value on WFPiConsole shows 0.22" today whereas Tempest station app on iphone shows 0.49" today.

WFPiConsole version is the newest.
RPi OS is Bullseye.
Rpi is a 3B.

![image](https://github.com/peted-davis/WeatherFlow_PiConsole/assets/119867548/9fa9f020-b808-4bed-8bee-b3be94f97291)

**Comment by peted-davis** [comment]
This will be because the phone is showing NC rain totals, while the PiConsole is showing raw rain totals. If you toggle NC rain off on the phone, the totals should match up

**Comment by geewizard1** [comment]
Thank you!
