### ISSUE TITLE
Set up issues

### ISSUE THREAD

**Issue by DMEbner** [peted-davis/WeatherFlow_PiConsole#134]
Good evening-

I recently had issues updating to the current version and I re-imaged my SD card and started over. I installed pi following the normal instructions, however, this time around it didn't send me through the set up module. I.e., couldn't put in device_ID, set location, etc. Can you provide me with some guidance?

Cheers!

**Comment by peted-davis** [comment]
You will only be prompted to enter the station and device IDs etc when you first start the console. If you are not prompted, make sure you don't have an existing `wfpiconsole.ini` file in the `~/wfpiconsole` directory.
