### ISSUE TITLE
Screen Blanking

### ISSUE THREAD

**Issue by wrldtvlr** [peted-davis/WeatherFlow_PiConsole#135]
**Describe the bug**
Updated to 23.10.1 a few weeks ago. The screen on my pi4B is now blanking after a few minutes. I did an apt upgrade at the same time, so I'm not sure what caused the blanking. I did not see an option for this is the wfpiconsole settings. Is this a change I need to make through the GUI?

**Comment by peted-davis** [comment]
This isn't something that is caused by the PiConsole. Screen blanking is set by the OS itself, so you might need to do some Googling to find how to fix it
