### ISSUE TITLE
Time display is jerky.

### ISSUE THREAD

**Issue by geewizard1** [peted-davis/WeatherFlow_PiConsole#136]
The latest version is making the time updates no longer smoothly incrementing.  The seconds digits jump from one value to several seconds ahead.  And that increment is variable.
Is this just the way it is?

WFPiConsole version is the newest.
RPi OS is Bullseye.
Rpi is a 3B.

**Comment by peted-davis** [comment]
I've been away for a while so haven't been able to reply. Do you still see this issue?

**Comment by geewizard1** [comment]
Yes, it is still occuring.

Bob

**Comment by peted-davis** [comment]
Ok I suspect to a degree this is just the way it is now. A Pi3 is old hardware compared to the Pi4 and Pi5, and many of the underlying graphics modules are optimised to work on the newer hardware (something that is out of my control), which often comes at cost when running on older hardware

**Comment by geewizard1** [comment]
No worries.  Thanks for getting back to me.
