### ISSUE TITLE
No brightness or illuminance for some stations

### ISSUE THREAD

**Issue by Qhilm** [peted-davis/WeatherFlow_PiConsole#137]
**Describe the bug**
I see "brightness" for some tempest stations (e.g. 5074) but after integration in Home Assistant there is no brightness or illuminance sensor somehow.

**To Reproduce**
1. Go to [tempest web page](https://tempestwx.com/map/5074/46.1476/30.6564/4) and check the station reports "brightness"
2. Add corresponding station to integration (e.g. 5074)
3. Observe there is no brightness or illuminance entity created.

**Screenshots**

<img width="392" alt="image" src="https://github.com/peted-davis/WeatherFlow_PiConsole/assets/3350433/d3cd9502-048d-4ace-bb0b-2765361da2a9">

<img width="574" alt="image" src="https://github.com/peted-davis/WeatherFlow_PiConsole/assets/3350433/46ca336f-2cd6-45a2-8b9a-e017aadec84f">

**Hardware/OS/Version (please complete the following information):**
 - OS: Home Assistant OS, 2023.12.3
 - Hardware: Pi4

**Comment by peted-davis** [comment]
This issues seems to be related to Home Assistant, no the PiConsole
