### ISSUE TITLE
Forecast Limited to next hour

### ISSUE THREAD

**Issue by rcrum003** [peted-davis/WeatherFlow_PiConsole#14]
This may be a personal preference, but can we make the forecast for the day, instead of the hour?

For example, when I leave the house in the morning, seeing what the forecast high/low helps me prepare for the day.
Seeing the high/low for the next hour isn't useful.

**Comment by dethompson1958** [comment]
Yes, looks good but a 12 or 24 hour would be more useful.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rcrum003** [comment]
Yes, 12 or 24 would be good.

**Comment by peted-davis** [comment]
Thanks for the suggestion. I am planning on revisiting the layout of the forecast panel soon, and will incorporate details from the daily forecast alongside the hourly values.

**Comment by dethompson1958** [comment]
Thanks.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by peted-davis** [comment]
A new forecast panel with both hourly and daily values in now available in Version 4.0
