### ISSUE TITLE
Update broke console

### ISSUE THREAD

**Issue by n7qnm** [peted-davis/WeatherFlow_PiConsole#143]
Got a message about an update - brought up a console and ran the update, now I'm getting prompted for a checkwx token.

Since I had you preconfigure, I've got NO login information, including for VNC to get a bigger terminal and interface.

Help!  (If can send me credentials, I can do the updates,

n7qnm@n7qnm.net
clayj@n7qnm.net

**Comment by peted-davis** [comment]
Not sure I fully understand what is going on here. The update should not overwrite the configuration file. That being said, you need to register here: https://www.checkwxapi.com/ to get a checkwx token that is required for the console to operate fully. If you don't know you login details and bought the console preconfigured, get in touch with the person who sold it to you. I have never sold preconfigured consoles
