### ISSUE TITLE
Request for Illuminance

### ISSUE THREAD

**Issue by pjmpessers** [peted-davis/WeatherFlow_PiConsole#145]
Instead of Solar radiation I prevere to get the Illuminance or better yet both on the panel. Is there a way to change the script so that i can show that on my WFPICONSOLE? Thanks.

**Comment by peted-davis** [comment]
This isn't possible in the main code - I suggest you think about developing a [custom panel](https://github.com/peted-davis/WeatherFlow_PiConsole?tab=readme-ov-file#advanced-custom-panels) that displays the information you wish to see. You can base this custom panel on existing built-in panel that shows solar radiation and just change the fields that you wish
