### ISSUE TITLE
Wont start after update...

### ISSUE THREAD

**Issue by BoatGod** [peted-davis/WeatherFlow_PiConsole#146]
**Describe the bug**

**To Reproduce**
boatgod@boatgod-305V4A-305V5A-3415VA:~/wfpiconsole$ wfpiconsole start
Traceback (most recent call last):
  File "/home/boatgod/wfpiconsole/main.py", line 37, in <module>
    from lib     import config as configFile
  File "/home/boatgod/wfpiconsole/lib/config.py", line 19, in <module>
    from kivy.logger    import Logger
ModuleNotFoundError: No module named 'kivy'

**Comment by peted-davis** [comment]
This a strange. Can you take a backup of your `wfpiconsole.ini` file and then delete the entire `wfpiconsole` directory. Once you have done that, try installing the console again using 

`curl -sSL https://peted-davis.github.io/wfpiconsole | bash`

Does it run after the install has finished?

**Comment by BoatGod** [comment]
After many hours of messing around, I came to the conclusion that wfpiconsole doesn't like the update that Kunbutu made. So, I reverted to an earlier flavor of Kunbutu and everything works again. Thanks for your work on this!

**Comment by peted-davis** [comment]
Great! Glad you are up and running again. I have never tried to run the PiConsole on Kunbutu, so it is hard to comment on what the reason is. Are you running on a Raspberry Pi or a PC? If I get a chance, I will try and replicate the error

**Comment by BoatGod** [comment]
running on an old laptop, lol!


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
