### ISSUE TITLE
Installed and when  I run console program goes back to user prompt.,   

### ISSUE THREAD

**Issue by hamgeek73** [peted-davis/WeatherFlow_PiConsole#147]
attached is the log when I go to start.  PS:  This is my first raspberry pi so could be  rookie mistake on my part.   
[wfpiconsole.log](https://github.com/user-attachments/files/15859830/wfpiconsole.log)

**Describe the bug**
Terminal goes back to prompt.

**To Reproduce**
start app.'

**Screenshots**

**Hardware/OS/Version (please complete the following information):**
 - OS: [e.g. Raspberry Pi  32 bitOS Bullseye]
 - Hardware:  Rapberry Pi 4 1GIG
 - Console Version: [just downloaded]

**Additional context**

**Comment by peted-davis** [comment]
Thanks for this bug report. I've traced the issue to installing the demo configuration file during the initial setup. I should be able to get a fix in place pretty quickly. In the meantime I would respond `n` to using the demo configuration file and then you'll be taken through the full setup process without issue

**Comment by peted-davis** [comment]
OK, this should now be fixed in v24.6.2. If you run the install command again, you should get a copy of the new code with the bug fix
