### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by hamgeek73** [peted-davis/WeatherFlow_PiConsole#148]
Thanks for last fix, now having configuration issues..   Not getting the prompt to enter the tempest  or weather underground keys I entered them manually in the wpficonsole.ini along with serial number and station id.   Attached are the errors I'm getting.   Error reads like it is the station ID should be an integer and it is.   

[wfpiconsole.log](https://github.com/user-attachments/files/15894689/wfpiconsole.log)

**Comment by peted-davis** [comment]
Make sure to delete any existing `wfpiconsole.ini` file. Then start the console with `wfpiconsole start`. You will be asked whether you want to install a minimal configuration file for demonstration purposes. Answer `n` to this question. Then you will be taken through the setup and asked to enter your API keys and station details. 

You will need your WeatherFlow Key and a CheckWX key (not a Weather Underground key). Please read the GitHub `README` which points you in the direction of the information you need.

**Comment by hamgeek73** [comment]
Thank you  That was the trick.

 

Ed Wiest

 ***@***.***> ***@***.***

614-284-1101
