### ISSUE TITLE
Install on Ubuntu 24.04.1 LTS

### ISSUE THREAD

**Issue by bleeblak8** [peted-davis/WeatherFlow_PiConsole#150]
My WeatherFlow Console Ubuntu x86 device updated to the latest version of Ubunut LTS.  Weatherflow fails to start.
In troubleshooting, I spun up 2 brand new VMs that are using the following versions.

VM1 - Ubuntu 22.04.5 LTS
Python 3.10-venv
WeatherFlowPiConsole installs just fine.

VM2 - Ubuntu 24.04.1 LTS
Python 3.12-venv
WeatherFlowPiConsole install script fails with error - Failed building wheel for kivy.
It also gives an error, Unable to install Kivy Python library- Its trying to install Kivy-2.2.0.

Not sure if the kivy install script doesn't work with the version of Ubuntu and Python. 

I can certainly roll back but wanted to make you aware that it breaks in 24.04.1 LTS.

**Comment by peted-davis** [comment]
Thanks for the report. I suspect there are no pre-compiled Kivy wheels for Python 3.12, and the installer is failing as it can't compile Kivy from source (missing dependencies). I suggest rolling back to 22.04 and waiting for the Kivy team to roll out updated wheels

**Comment by bleeblak8** [comment]
Thanks, I ended up doing just that.  Much appreciated.
