### ISSUE TITLE
token not authorized

### ISSUE THREAD

**Issue by pmendiuk** [peted-davis/WeatherFlow_PiConsole#27]
Hello,
I am trying to set up another WeatherFlow_PiConsole and I am receiving an error when entering the token:

Access not authorized. Please re-enter your CheckWX API key*:

**Comment by peted-davis** [comment]
Did you manage to solve this? Usually this happens because the API key is incorrectly copied into the PiConsole

**Comment by pmendiuk** [comment]
Yes there was an issue with Windows clip board.
