### ISSUE TITLE
Today rain one number after the comma.

### ISSUE THREAD

**Issue by pjmpessers** [peted-davis/WeatherFlow_PiConsole#28]
Is it possible to see the today rain with one number after the comma? Just like the yesterday rain does?

**Comment by peted-davis** [comment]
Usually the number of decimal places depends on the amount of rain that has fallen. As the amount goes up, I restrict the number of digits to ensure it displays nicely without being too squished. What units are you using?

**Comment by pjmpessers** [comment]
I use a raspberry pi 4 4gb with the PI touchdisplay 7 inch. The wfpiconsole is the 4.0.1

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: peted-davis<mailto:notifications@github.com>
Verzonden: donderdag 31 december 2020 19:11
Aan: peted-davis/WeatherFlow_PiConsole<mailto:WeatherFlow_PiConsole@noreply.github.com>
CC: Pieter<mailto:pieterpessers@hotmail.com>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [peted-davis/WeatherFlow_PiConsole] Today rain one number after the comma. (#28)


Usually the number of decimal places depends on the amount of rain that has fallen. As the amount goes up, I restrict the number of digits to ensure it displays nicely without being too squished. What units are you using?

**Comment by peted-davis** [comment]
Sorry, I meant what units do you use to display the rain accumulation? I assume either centimeters or millimeters.

**Comment by pjmpessers** [comment]
Sorry. My mistake. It is in mm. The today rain and yesterday rain. Yesterday rain is in one number after the comma.

By the way. Have a great 2021.


[cid:image002.jpg@01D6DFAA.47614640]

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: peted-davis<mailto:notifications@github.com>
Verzonden: donderdag 31 december 2020 19:18
Aan: peted-davis/WeatherFlow_PiConsole<mailto:WeatherFlow_PiConsole@noreply.github.com>
CC: Pieter<mailto:pieterpessers@hotmail.com>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [peted-davis/WeatherFlow_PiConsole] Today rain one number after the comma. (#28)


Sorry, I meant what units do you use to display the rain accumulation? I assume either centimeters or millimeters.

**Comment by peted-davis** [comment]
Not a problem. For millimeters when the total rainfall is greater than 10 mm, no number will be displayed after the comma. I assume this is what you are seeing. The Today rain is greater than 10, and the yesterday rain is less than 10. 

If you are comfortable editing the code it is easy to change this on lines 240-243 in the file `lib/observationFormat.py`. If you make a change though, be careful updating to new versions as this change will be overwritten

**Comment by pjmpessers** [comment]
is it in line 240 making the 10 into 1?

**Comment by peted-davis** [comment]
Not quite, but close. The easiest way to fix this is to replace the `{:.0f}` on line 243 with `{:.1f}`. Basically line 243 and 241 should be exactly the same.

**Comment by pjmpessers** [comment]
Thank you. You helped a lot. When i'm back home i let you know if that works.


-------- Oorspronkelijk bericht --------
Van: peted-davis <notifications@github.com>
Datum: 31-12-2020 19:55 (GMT+01:00)
Aan: peted-davis/WeatherFlow_PiConsole <WeatherFlow_PiConsole@noreply.github.com>
Cc: Pieter <pieterpessers@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [peted-davis/WeatherFlow_PiConsole] Today rain one number after the comma. (#28)


Not quite, but close. The easiest way to fix this is to replace the {:.0f} on line 243 with {:.1f}. Basically line 243 and 241 should be exactly the same.

**Comment by pjmpessers** [comment]
Thank you very much. It seems that this did the trick. I wait till the next rain
