### ISSUE TITLE
"No module named distro"

### ISSUE THREAD

**Issue by wx-jc** [peted-davis/WeatherFlow_PiConsole#29]
Just installed this on Ubuntu 18.04 running in a virtual environment, and got the following error when trying to start it:
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    from lib     import config as configFile
  File "/home/jcook/wfpiconsole/lib/config.py", line 27, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'

It showed that it got installed (check mark in the install status).

**Comment by peted-davis** [comment]
Huh, that's weird. Try installing it manually with `python3 -m pip install distro` and then see if the console runs.

**Comment by wx-jc** [comment]
Ok that seemed to work.  I tried installing it manually but it didn't work when I tried it, but with that command it did.  Thanks!

**Comment by peted-davis** [comment]
Cool! Glad it's working. I'll have a dig around and see if I can work out why this didn't work out of the box.
