### ISSUE TITLE
Installer Failed on Pi 4 Model B

### ISSUE THREAD

**Issue by NickT-in-SD** [peted-davis/WeatherFlow_PiConsole#32]
I ran the installation script per the instructions on this site, but the installer failed with the following:

"Error: unable to install Python module: autobahn[twisted]"
"error: can not find Rust Compiler"
"ERROR: Failed building wheel for cryptography"
"ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed correctly"

**Comment by peted-davis** [comment]
Sorry you ran into issues. I have looked into this and unfortunately there have been some big changes to the Python cryptography module that I need to deal with. In the meantime, run this command in a terminal:

`python3 -m pip install cryptography==3.3.2`

and then try installing the PiConsole again. Hopefully this time everything will go smoothly.

**Comment by NickT-in-SD** [comment]
Thank you! That worked.

**Comment by peted-davis** [comment]
This should now be fixed in v4.0.3
