### ISSUE TITLE
4.0.3 update error

### ISSUE THREAD

**Issue by wx-jc** [peted-davis/WeatherFlow_PiConsole#33]
[i] Updating WeatherFlow PiConsole Python modules...
  [✓] Updating Python package manager
  [✗] Updating Python module
  Error: Unable to update Python module: numpy

 /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
ERROR: Could not find a version that satisfies the requirement numpy==1.20.1
ERROR: No matching distribution found for numpy==1.20.1

**Comment by peted-davis** [comment]
Sorry you're having an issue. Can you let me know the hardware you are using, and your Python version?

**Comment by wx-jc** [comment]
This is on an older intel computer running Ubuntu 18.04.  Python 3 version
is 3.6.9.

**Comment by peted-davis** [comment]
Ok, I see the error I made. I'll work on a fix

**Comment by peted-davis** [comment]
OK, this should now be fixed. Can you try running `wfpiconsole update` again please?

**Comment by wx-jc** [comment]
That did the trick.  Thanks for the quick fix!
