### ISSUE TITLE
Station in low battery causes errors

### ISSUE THREAD

**Issue by cefoster0** [peted-davis/WeatherFlow_PiConsole#43]
My Tempest station has been in mode 3 for several days as was new in box and only got one morning of sun before a week of rain and clouds here in the north east. After the station went into mode 3 a couple days ago, I noticed dashes across most of the display values. 

Running interactively, I saw the following errors:
   File "/home/pi/wfpiconsole/lib/derivedVariables.py", line 838, in MeanWindSpeed
2022-01-01 17:04:18-0500 [-]     AvgWind = [Sum/Length,'mps',Sum/Length,Length,Now]
2022-01-01 17:04:18-0500 [-] ZeroDivisionError: division by zero

It looks like since since my system is so new and has been in mode 2/3 for so long, I do not have valid wind data coming out of the api. 

I added a check. on 838 on the length value out of windups
 Length = len(windSpd)
            if Length > 0:

I also had to add another check and to line 896 
not math.isnan(windGust[0]):

That got most of the data that is populating working , except the 'feels like' temperature. which is odd as feels like shows up in the regular app/website. 

my station # is 47521 if you can peak via the API to see what's going on.

**Comment by cefoster0** [comment]
Adding some photos. I reset the sizing code changes I made in the other ticket with no change. 
![5CF2447B-97E4-4463-A504-6DA01148E58F](https://user-images.githubusercontent.com/75394816/147863169-6a505567-d653-473d-b159-79ffaa75ab1f.jpeg)
![13A23816-ED0F-41C6-80A9-4AC1B9C1FBF1](https://user-images.githubusercontent.com/75394816/147863170-dd0e3c02-7df7-4061-b964-3be0aea5283d.jpeg)
![C9F6E706-56EB-44AA-B3B8-BF9BFE3C29ED](https://user-images.githubusercontent.com/75394816/147863171-93d8ee79-4b56-4655-b3a8-66ccb6974fdb.jpeg)

**Comment by peted-davis** [comment]
Unfortunately this is a known bug and there is going to be a fix in the next, long overdue, update. Sorry it is causing you issues!

**Comment by peted-davis** [comment]
This should now be fixed in the latest version (v22.3.1)
