### ISSUE TITLE
screen touches not recognized

### ISSUE THREAD

**Issue by ctgreybeard** [peted-davis/WeatherFlow_PiConsole#48]
Referencing issue #8 

After the recent update this has occurred again, no touches are recognized in the application. I tried adding the line to the kivy config but that did not correct the problem.

**Comment by peted-davis** [comment]
Under the `[Display]` section in `wfpiconsole.ini`, make sure the `Cursor` key is set to `0`. This is something I am looking into

**Comment by ctgreybeard** [comment]
That did it. It was set to "1".

**Comment by peted-davis** [comment]
This should now be fixed, so I am going to close the issue
