### ISSUE TITLE
Updating to v22.3.2 fails.

### ISSUE THREAD

**Issue by mbeilste** [peted-davis/WeatherFlow_PiConsole#49]
Getting an error on a few of the objects during the update.

![PXL_20220311_025814718](https://user-images.githubusercontent.com/4382383/157793825-55dc0bde-4a75-45d5-8a85-84b52dc53fc7.jpg)

**Comment by peted-davis** [comment]
This looks like you have some corrupted files on your system. I would suggest that you take a backup of your `wfpiconsole.ini` file and then delete the entire PiConsole directory with `rm -rf ~/wfpiconsole/`

Fetch a new copy by running the install script

**Comment by mbeilste** [comment]
Thanks!  That worked and got me updated.  I am now getting this when I try to start it.
![Uploading PXL_20220316_114029492.jpg…]()

**Comment by mbeilste** [comment]
Thanks! That worked and got me updated. I am now getting this when I try to start it.

![PXL_20220316_114029492](https://user-images.githubusercontent.com/4382383/158582717-9be41821-c214-4493-97c9-38faa3ecc754.jpg)

**Comment by mbeilste** [comment]
That did it.  Thank you sir!  Much appreciated!
