### ISSUE TITLE
Crash after tap lightning

### ISSUE THREAD

**Issue by KrunchMuffin** [peted-davis/WeatherFlow_PiConsole#52]
**Describe the bug**
New station. Clicked lighting tab and crashed.

**To Reproduce**
Tapping lightning tab with new station.

**Screenshots**
![IMG_20220326_010052](https://user-images.githubusercontent.com/1037197/160225522-594515fc-0f5f-45df-ba71-a7857dbde0d1.jpg)

**Hardware/OS/Version (please complete the following information):**
 - OS: [Raspberry Pi OS Bullseye]
 - Hardware: [Pi4]
 - Console Version: [22.3.2]

**Additional context**
I know Python, but not Kivy. I was going to fix it but figured I'd post. 
I don't know if you can do it, but I think it should be `app.CurrentConditions.Obs['StrikeDeltaT'][4] is not None and...`

**Comment by peted-davis** [comment]
Thanks for the report. You're right that I need to check for the `None` condition. I will get this fixed in the next version

**Comment by peted-davis** [comment]
This should now be fixed in v22.3.3
