### ISSUE TITLE
wfpiconsole crash with lightning in first panel

### ISSUE THREAD

**Issue by pjmpessers** [peted-davis/WeatherFlow_PiConsole#53]
I love wfpiconsole and so installed v22.3.3. But it crashed untill i deleted wtpiconsole.ini. After that it worked again untill i set the lightning in panel one. Then it crashes again untill i delete wfpiconsole again. So setting the lightning in the first panel instead of the normal panel two is a problem now.

**Comment by peted-davis** [comment]
Sorry about this! I fixed one bug with the lightning panel, which introduced a new one. There will be a new release by the end of today/tomorrow with this fixed

**Comment by pjmpessers** [comment]
Not a problem. Happy that there will be a fix.

**Comment by peted-davis** [comment]
This is fixed in v22.3.4

**Comment by pjmpessers** [comment]
It worked. I can select lightning in the first panel again. Thanks.
