### ISSUE TITLE
difficult to see rain intensity gauge with TFT monitor.

### ISSUE THREAD

**Issue by pjmpessers** [peted-davis/WeatherFlow_PiConsole#55]
Hello.

Still love the wfpiconsole, but with a TFT monitor it is difficult to see the rain intensity gauge. This only has a good vissibillity when i'm standing right in front of the monitor. 

I worked around this in the previous versions by making a new raingauge.png, but this doen't work anymore in the newer version.  I named my own reworked raingauge.png rainintensity_hR.png and rainintensity_IR.png and placed it in /home/pi/wfpiconsole/icons/misc, but i then only saw a white block. 

Is there a way to make the raingauge less transparant?

Thanks.

**Comment by peted-davis** [comment]
This should work. Make sure the icons are called `rainIntensity_lr.png` and `rainIntensity_hr.png` (the `I` in `Intensity` is capitalised`).

**Comment by pjmpessers** [comment]
It does work. But the problem is the transparency. I prefer to have no transparency. When you look at the monitor at a angle it is very difficult to the raingauge. I would like to know if there is a possibility to change the transparency of the raingauge graphic?

**Comment by pjmpessers** [comment]
That is great. Thank you.👍🏻

**Comment by peted-davis** [comment]
I've uploaded the files to WeTransfer and you should be able to download the files here: https://we.tl/t-GkHKrWsXNs

**Comment by pjmpessers** [comment]
Thanks for your support, Peted-davis. appreciate it. Is this a already modified file, or is it still necessary to modify?

**Comment by peted-davis** [comment]
They still need editing. I'll try and send edited versions in a couple of days if that would be useful?

**Comment by pjmpessers** [comment]
I think i got it. Now it is only a matter of waiting if it worked.
