### ISSUE TITLE
Update unable to fetch station data

### ISSUE THREAD

**Issue by raybarton** [peted-davis/WeatherFlow_PiConsole#59]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Hardware/OS/Version (please complete the following information):**
 - OS: [e.g. Raspberry Pi OS Bullseye]
 - Hardware: [e.g. Pi3]
 - Console Version: [e.g. 22.3.1]

**Additional context**

**Comment by peted-davis** [comment]
Delete the `wfpiconsole.ini` file and then restart the console. You'll be prompted to enter the details of your new setup

**Comment by raybarton** [comment]
Thank you

Ray Barton
908.309.2222

On Jun 2, 2022, at 2:08 AM, peted-davis ***@***.***> wrote:

﻿

Delete the wfpiconsole.ini file and then restart the console. You'll be prompted to enter the details of your new setup

**Comment by raybarton** [comment]
IT worked perfect…thank you so much….love this thng

Ray Barton
908-309-2222
