### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by kward-32767** [peted-davis/WeatherFlow_PiConsole#6]
HI!

Thank you for this project!  Followed your instructions and run into the following when starting up . . . 

$ wfpiconsole start
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_20-06-10_8.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/home/pi/.local/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0'>
[INFO   ] [GL          ] OpenGL vendor <b'Broadcom'>
[INFO   ] [GL          ] OpenGL renderer <b'VideoCore IV HW'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
2020-06-10 15:19:17-0400 [-] Log opened.
2020-06-10 15:19:20-0400 [-] Starting factory <__main__.WeatherFlowClientFactory object at 0xb5f2d750>
Unable to connect to X server
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event3
[INFO   ] [MTD         ] Read event from </dev/input/event3>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [MTD         ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [MTD         ] Read event from </dev/input/event2>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [MTD         ] Read event from </dev/input/event0>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event3
[INFO   ] [HIDInput    ] Read event from </dev/input/event3>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [HIDInput    ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [HIDInput    ] Read event from </dev/input/event2>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [MTD         ] </dev/input/event3> range position X is 0 - 0
[INFO   ] [MTD         ] </dev/input/event3> range position Y is 0 - 0
[INFO   ] [MTD         ] </dev/input/event1> range position X is 0 - 0
[INFO   ] [MTD         ] </dev/input/event2> range position X is 0 - 0
[INFO   ] [MTD         ] </dev/input/event2> range position Y is 0 - 0
[INFO   ] [MTD         ] </dev/input/event1> range position Y is 0 - 0
[INFO   ] [MTD         ] </dev/input/event3> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range position X is 0 - 0
[INFO   ] [MTD         ] </dev/input/event2> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event1> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event3> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range position Y is 0 - 0
[INFO   ] [MTD         ] </dev/input/event3> range pressure is 0 - 255
[INFO   ] [HIDMotionEvent] using <Logitech USB Keyboard System Control>
[INFO   ] [MTD         ] </dev/input/event1> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event2> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range touch major is 0 - 0
[INFO   ] [HIDMotionEvent] using <Logitech USB Keyboard>
[INFO   ] [HIDMotionEvent] using <Logitech USB Keyboard Consumer Control>
[INFO   ] [MTD         ] </dev/input/event3> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event1> range pressure is 0 - 255
[INFO   ] [HIDMotionEvent] using <USB OPTICAL MOUSE>
[INFO   ] [Support     ] Starting twisted reactor
[INFO   ] [MTD         ] </dev/input/event0> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event0> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event3> rotation set to 0
[INFO   ] [MTD         ] </dev/input/event1> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event2> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event1> rotation set to 0
[INFO   ] [MTD         ] </dev/input/event2> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event2> rotation set to 0
[INFO   ] [MTD         ] </dev/input/event0> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event0> rotation set to 0
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Leaving application in progress...
[INFO   ] [Support     ] Stopping twisted threads
[INFO   ] [Support     ] Shutting down twisted reactor
2020-06-10 15:19:25-0400 [-] Traceback (most recent call last):
2020-06-10 15:19:25-0400 [-]   File "main.py", line 1043, in <module>
2020-06-10 15:19:25-0400 [-]     wfpiconsole().run()
2020-06-10 15:19:25-0400 [-]   File "/home/pi/.local/lib/python3.7/site-packages/kivy/app.py", line 855, in run
2020-06-10 15:19:25-0400 [-]     runTouchApp()
2020-06-10 15:19:25-0400 [-]   File "/home/pi/.local/lib/python3.7/site-packages/kivy/base.py", line 504, in runTouchApp
2020-06-10 15:19:25-0400 [-]     EventLoop.window.mainloop()
2020-06-10 15:19:25-0400 [-]   File "/home/pi/.local/lib/python3.7/site-packages/kivy/core/window/window_egl_rpi.py", line 94, in mainloop
2020-06-10 15:19:25-0400 [-]     self._mainloop()
2020-06-10 15:19:25-0400 [-]   File "/home/pi/.local/lib/python3.7/site-packages/kivy/core/window/window_egl_rpi.py", line 89, in _mainloop
2020-06-10 15:19:25-0400 [-]     EventLoop.idle()
2020-06-10 15:19:25-0400 [-]   File "/home/pi/.local/lib/python3.7/site-packages/kivy/base.py", line 339, in idle
2020-06-10 15:19:25-0400 [-]     Clock.tick()
2020-06-10 15:19:25-0400 [-]   File "/home/pi/.local/lib/python3.7/site-packages/kivy/clock.py", line 591, in tick
2020-06-10 15:19:25-0400 [-]     self._process_events()
2020-06-10 15:19:25-0400 [-]   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
2020-06-10 15:19:25-0400 [-]   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
2020-06-10 15:19:25-0400 [-]   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
2020-06-10 15:19:25-0400 [-]   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
2020-06-10 15:19:25-0400 [-] TypeError: create_window() takes 1 positional argument but 2 were given
$ uname -a
Linux raspberrypi 4.19.118+ #1311 Mon Apr 27 14:16:15 BST 2020 armv6l GNU/Linux
$ python -V
Python 3.7.3

. . .  Here's the output of /home/pi/.kivy/logs/kivy_20-06-10_8.txt . . . 

$ cat /home/pi/.kivy/logs/kivy_20-06-10_8.txt
[INFO   ] Logger: Record log in /home/pi/.kivy/logs/kivy_20-06-10_8.txt
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "/home/pi/.local/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0]
[INFO   ] Python: Interpreter at "/usr/bin/python3"
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] Window: Provider: egl_rpi
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <gl>
[INFO   ] GL: OpenGL version <b'OpenGL ES 2.0'>
[INFO   ] GL: OpenGL vendor <b'Broadcom'>
[INFO   ] GL: OpenGL renderer <b'VideoCore IV HW'>
[INFO   ] GL: OpenGL parsed version: 2, 0
[INFO   ] GL: Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] GL: Texture max size <2048>
[INFO   ] GL: Texture max units <8>
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: sdl2
[INFO   ] ProbeSysfs: device match: /dev/input/event3
[INFO   ] MTD: Read event from </dev/input/event3>
[INFO   ] ProbeSysfs: device match: /dev/input/event1
[INFO   ] MTD: Read event from </dev/input/event1>
[INFO   ] ProbeSysfs: device match: /dev/input/event2
[INFO   ] MTD: Read event from </dev/input/event2>
[INFO   ] ProbeSysfs: device match: /dev/input/event0
[INFO   ] MTD: Read event from </dev/input/event0>
[INFO   ] ProbeSysfs: device match: /dev/input/event3
[INFO   ] HIDInput: Read event from </dev/input/event3>
[INFO   ] ProbeSysfs: device match: /dev/input/event1
[INFO   ] HIDInput: Read event from </dev/input/event1>
[INFO   ] ProbeSysfs: device match: /dev/input/event2
[INFO   ] HIDInput: Read event from </dev/input/event2>
[INFO   ] ProbeSysfs: device match: /dev/input/event0
[INFO   ] HIDInput: Read event from </dev/input/event0>
[INFO   ] Base: Start application main loop
[INFO   ] MTD: </dev/input/event3> range position X is 0 - 0
[INFO   ] MTD: </dev/input/event3> range position Y is 0 - 0
[INFO   ] MTD: </dev/input/event1> range position X is 0 - 0
[INFO   ] MTD: </dev/input/event2> range position X is 0 - 0
[INFO   ] MTD: </dev/input/event3> range touch major is 0 - 0
[INFO   ] MTD: </dev/input/event1> range position Y is 0 - 0
[INFO   ] MTD: </dev/input/event2> range position Y is 0 - 0
[INFO   ] MTD: </dev/input/event0> range position X is 0 - 0
[INFO   ] MTD: </dev/input/event2> range touch major is 0 - 0
[INFO   ] MTD: </dev/input/event1> range touch major is 0 - 0
[INFO   ] MTD: </dev/input/event3> range touch minor is 0 - 0
[INFO   ] MTD: </dev/input/event0> range position Y is 0 - 0
[INFO   ] MTD: </dev/input/event3> range pressure is 0 - 255
[INFO   ] MTD: </dev/input/event1> range touch minor is 0 - 0
[INFO   ] HIDMotionEvent: using <Logitech USB Keyboard System Control>
[INFO   ] HIDMotionEvent: using <Logitech USB Keyboard Consumer Control>
[INFO   ] MTD: </dev/input/event2> range touch minor is 0 - 0
[INFO   ] MTD: </dev/input/event0> range touch major is 0 - 0
[INFO   ] HIDMotionEvent: using <Logitech USB Keyboard>
[INFO   ] MTD: </dev/input/event3> axes invertion: X is 0, Y is 0
[INFO   ] MTD: </dev/input/event1> range pressure is 0 - 255
[INFO   ] MTD: </dev/input/event3> rotation set to 0
[INFO   ] HIDMotionEvent: using <USB OPTICAL MOUSE>
[INFO   ] MTD: </dev/input/event1> axes invertion: X is 0, Y is 0
[INFO   ] MTD: </dev/input/event0> range touch minor is 0 - 0
[INFO   ] Support: Starting twisted reactor
[INFO   ] MTD: </dev/input/event2> range pressure is 0 - 255
[INFO   ] MTD: </dev/input/event0> range pressure is 0 - 255
[INFO   ] MTD: </dev/input/event1> rotation set to 0
[INFO   ] MTD: </dev/input/event2> axes invertion: X is 0, Y is 0
[INFO   ] MTD: </dev/input/event2> rotation set to 0
[INFO   ] MTD: </dev/input/event0> axes invertion: X is 0, Y is 0
[INFO   ] MTD: </dev/input/event0> rotation set to 0
[INFO   ] GL: NPOT texture support is available
[INFO   ] Base: Leaving application in progress...
[INFO   ] Support: Stopping twisted threads
[INFO   ] Support: Shutting down twisted reactor

Happy to supply anything else you might need.  As far as a replacement for darksky, have you thought to use weatherunderground.com (https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY/edit) ??

Thank you, again for this project I hope to have it displaying my new Tempest wether data real soon!

-Keith

**Comment by peted-davis** [comment]
Thanks for the sharing the output. I will adjust the code accordingly.
