### ISSUE TITLE
Wfpiconsole fails in Sager routines

### ISSUE THREAD

**Issue by ctgreybeard** [peted-davis/WeatherFlow_PiConsole#68]
**Describe the bug**
I noticed that my weather screens were down this evening. Restarting it fails.

**To Reproduce**
1. Try to start the weather console

**Screenshots**
None

**Hardware/OS/Version (please complete the following information):**
 - OS: Raspberry Pi Buster
 - Hardware: PI4
 - Console Version: 22.5.1

**Additional context**
Log shows error in Sager

[wfpiconsole.log](https://github.com/peted-davis/WeatherFlow_PiConsole/files/10145490/wfpiconsole.log)

**Comment by Grandmasg** [comment]
Found a temp fix.. /home/pi/wfpiconsole/lib/sager.py", line 266
`
            #self.sager_data['METAR'] = Data.json()['data'][0]
            self.sager_data['METAR'] = ''
`
<img width="456" alt="temp fix" src="https://user-images.githubusercontent.com/6714237/205428514-ed9047a7-772f-4cbc-a838-3bd1c2eb4405.png">

**Comment by peted-davis** [comment]
Thanks for the report, I will look into this ASAP (probably Monday at the latest)

**Comment by creas002** [comment]
Sager causing same issue for me as well.

![image](https://user-images.githubusercontent.com/69941625/205440270-40cba00e-4c0a-4dc0-b374-6275e7dc8398.png)

**Comment by bgiuriceo** [comment]
Same with me 
<img width="840" alt="wfpiconsole error" src="https://user-images.githubusercontent.com/50047233/205443135-67f0669d-5fc4-4e40-b637-066065ad96d8.png">

**Comment by pjmpessers** [comment]
That code did work for me. Thank you. I can use wfpiconsole again. Great.
I will wait for the fix, but happy that i can use the console again.

**Comment by KrunchMuffin** [comment]
So there is no data coming back from the METAR API, so instead of making it empty and I added an AND to check for length so when the API comes back it will work again.

```
 if checkwx_api.verify_response(Data, 'data') and len(Data.json()['data']):
```

**Comment by peted-davis** [comment]
This should now be fixed in v22.21.1.

To update please run `wfpiconsole stop` followed by `wfpiconsole update`. Please make sure any local changes to the code or custom panels are backed up.

**Comment by creas002** [comment]
> This should now be fixed in v22.12.1.
> 
> To update please run `wfpiconsole stop` followed by `wfpiconsole update`. Please make sure any local changes to the code or custom panels are backed up.

Thanks, new version resolved issue for me.

**Comment by pjmpessers** [comment]
Is there more changes in these codes? If not, is it possible to only update the sager.py?

**Comment by peted-davis** [comment]
> Is there more changes in these codes? If not, is it possible to only update the sager.py?

There are some other small bug fixes scattered throughout the update, but the changes to fix this particular bug are all in `sager.py`

**Comment by pjmpessers** [comment]
Thank you. I looked at the code which where new and only updated those. Works perfectly again. 👍🏻
