### ISSUE TITLE
will not complete update V22.12.1

### ISSUE THREAD

**Issue by john0500** [peted-davis/WeatherFlow_PiConsole#74]
will not complete update to v22.12.1

error : cannot lock ref/tags22.5.1": unable to resolve reference 'refs/tags/v22.5.1': reference broken

from https://github.com/peted-davis/WeatherFlow_Piconsole

**Comment by peted-davis** [comment]
Probably easiest to start with a clean set of files.

Assuming the PiConsole is installed in the default location, make a backup of your `wfpiconsole.ini` file and any custom panels you may have created. Delete the existing PiConsole files using `rm -rf ~/wfpiconsole/` and then run the install command again to fetch a clean set of files: `curl -sSL https://peted-davis.github.io/wfpiconsole | bash`
