### ISSUE TITLE
Can’t install

### ISSUE THREAD

**Issue by adamsfour** [peted-davis/WeatherFlow_PiConsole#79]
**Describe the bug**
trying to install software. When I run from terminal I get the following

![image](https://user-images.githubusercontent.com/122233494/211218415-eb9e5ce9-546d-4051-85fc-f83e1283607e.jpg)

here is a snap shot of version 
![image](https://user-images.githubusercontent.com/122233494/211218504-f2edeb9a-b993-4bad-aaf6-53c787e9082a.jpg)

Command I am running is curl -sSL https://peted-davis.github.io/w

**Comment by peted-davis** [comment]
Not sure if you've made a typo in your post, but the full command you need to run is 

`curl -sSL https://peted-davis.github.io/wfpiconsole | bash`

**Comment by adamsfour** [comment]
So that was the problem. Here is the line as it appears in instruction. Hence my confusion 
M
![CDD7F4E1-9361-480E-81B2-D51A70B79C9C](https://user-images.githubusercontent.com/122233494/211219991-0f68c1cb-4992-45c4-a83e-4dc0908c57af.png)

**Comment by peted-davis** [comment]
Great! Glad we managed to find a quick fix. Uncle the GitHub README formats 'code' on a single line, so the grey box has a horizontal scroll bar if your screen is not wide enough to show the full command. It is easy to miss. Hope you enjoy the console!

**Comment by adamsfour** [comment]
Thanks one stupid question. Once installed can I reach the display from any computer on my network.
