### ISSUE TITLE
Not a bug - a question

### ISSUE THREAD

**Issue by adamsfour** [peted-davis/WeatherFlow_PiConsole#80]
I finally have the WeatherFlow up and running ( thanks for the help) on a PI 4. Is there a way via either Remote Desktop of SSH to run remotely from a windows 11 workstation. 

thanks

**Comment by peted-davis** [comment]
Yes, if you run a VNC server on your Pi4 and a VNC viewer on your Windows 11 workstation, you should be able to see the PiConsole on the Windows 11 machine. 

More info here: https://www.raspberrypi.com/documentation/computers/remote-access.html#vnc
