### ISSUE TITLE
Install Script Crashes on Buster Pi 3B+

### ISSUE THREAD

**Issue by Death2Beavis** [peted-davis/WeatherFlow_PiConsole#82]
**Describe the bug**

**To Reproduce**
1. Go to Run install script "curl -sSL https://peted-davis.github.io/wfpiconsole | bash"
2. Click on OK to continue
3. Scroll down to (script runs, generates lots of debug)

**Screenshots**

Attached errors scraped from Pi terminal
[install errors.txt](https://github.com/peted-davis/WeatherFlow_PiConsole/files/10450526/install.errors.txt)

**Hardware/OS/Version (please complete the following information):**
 - OS: [e.g. Raspberry Pi OS Bullseye] Buster
 - Hardware: [e.g. Pi3] Pi3B+
 - Console Version: [e.g. 22.3.1] Unknown assume current

**Additional context**
This is a complete rebuild after console crashing (saw notes on bullseye, may be that issue). New SD card, new image of Buster, fully updated.

**Comment by peted-davis** [comment]
Sorry, this is a known bug that I haven't had a chance to fix yet. 

Please run this command before running the install command

`python3 -m pip install cryptography==37.0.4`

**Comment by Death2Beavis** [comment]
Thanks appreciate that
