### ISSUE TITLE
Not a Bug - Alarms 

### ISSUE THREAD

**Issue by disruptivepatternmaterial** [peted-davis/WeatherFlow_PiConsole#83]
Any thoughts on implementing alarms? I am happy to give it s crack but wanted to see if you had some idea of where to start in your code...

My idea is to start, make a conf file with upper and lower bounds for some measurements and then play a sound / make a symbol on the UI when one is violated.

Why do I want this? I use the panel to see what's up outside when I first wake up to walk the dog. I'd love to just be able to see a red ! to tell me it is cold enough that I have to find my mittens. HAHA

**Comment by peted-davis** [comment]
Yes, this could be done and it isn't something I have on my list so I am very happy for you to give it a try.

You can use the existing `wfpiconsole.ini` config file to hold the upper and lower bounds and to toggle the alerts on and off. Probably best to use a new `[alerts]` section. The sections in the config file are linked to the tabs in the `settings` screen so you can add the functionality there to allow the user to change the bounds from within the console and turn the alerts on and off. You'll need to edit `lib/config.py` to generate some default upper and lower bounds and set the default behaviour to alerts off. 

You'll then need to find somewhere in the code to check whether the alerts need to be triggered. Possibly in `lib/observationParser.py` which handles in coming messages from the websocket connection. The alert could either be a popup (perhaps something similar to the existing Update Notification) or a sound (you would need to read the Kivy docs - the underlying Python GUI package - to understand how to do this). You'll probably also need to give some thought to how often the alerts are triggered and how frequently they reset.

This could definitely be done, but it'll be quite a big project!
