### ISSUE TITLE
Failed installation 

### ISSUE THREAD

**Issue by adamsfour** [peted-davis/WeatherFlow_PiConsole#86]
Attempting to install on pi3 see screenshot for the error I received. 
![8EE99D86-B486-42C9-A637-6C93269D912C](https://user-images.githubusercontent.com/122233494/218193960-44e3b0eb-d318-4fff-85df-faec02d19e9e.jpeg)
![1C5C2D00-4C83-4951-8935-716E082773F4](https://user-images.githubusercontent.com/122233494/218193962-f06389f1-92df-4501-be08-956e20e1dae4.jpeg)
![1AF41FCB-AC7F-4E41-9F4B-D8A2C04F3802](https://user-images.githubusercontent.com/122233494/218193963-fd8d2150-f47c-48aa-94f6-f41ed7e4fe72.jpeg)
![68C0768C-9106-46E8-AA1F-C623F54F87B2](https://user-images.githubusercontent.com/122233494/218193966-59720cb8-70d6-43d4-a9fc-030c33c831f2.jpeg)

**Comment by adamsfour** [comment]
I figured a way to see error log[ 
[ErrorLog.txt](https://github.com/peted-davis/WeatherFlow_PiConsole/files/10711361/ErrorLog.txt)

**Comment by adamsfour** [comment]
Some logs 
[kivy_23-02-10_3.txt](https://github.com/peted-davis/WeatherFlow_PiConsole/files/10711666/kivy_23-02-10_3.txt)

**Comment by adamsfour** [comment]
Sorry another data point. Did a clean install of OS, ran the extra script you mention in a closed issue (python - m pip ) then ran install. No change.

**Comment by peted-davis** [comment]
I'm looking into this at the moment but I'm not having much luck I'm afraid. It looks like something has changed with Kivy and/or Raspberry Pi OS that is preventing Kivy from compiling correctly

**Comment by adamsfour** [comment]
Okay. I did try install without taking OS upgrade but made no difference. Do we think it’s isolated to PI 3B or would I get same result on PI 4B. Not my first choice but could purchase a PI 4 if only way forward. Will stand by

**Comment by adamsfour** [comment]
Would reverting to an older version of buster OS resolve the problem. I found earlier versions.

**Comment by peted-davis** [comment]
I think this is only Pi3 related. You could definitely try an older version of Buster. It might help isolate the issue. I'll keep working on finding a fix for the Pi3, no need to get a Pi4 right now

**Comment by adamsfour** [comment]
Tried 4-4-2022 buster build. Same error.

**Comment by adamsfour** [comment]
Also tired 12-02-2021 build which gave me the same error. Thanks for your help

**Comment by peted-davis** [comment]
Can you try running this command:

`python3 -m pip install https://kivy.org/downloads/2.1.0/Kivy-2.1.0.tar.gz`

If it works, it will take a while to compile

**Comment by adamsfour** [comment]
Yes, I will report back once completed. I assume you want me to 1) run Python3 script and then follow by Curl script

**Comment by peted-davis** [comment]
Yes, if the command I shared completes, then try the curl command again

**Comment by adamsfour** [comment]
Sorry no luck. I have attached the screen dump and the error log. Hope this helps
[kivy_23-02-12_3.txt](https://github.com/peted-davis/WeatherFlow_PiConsole/files/10717213/kivy_23-02-12_3.txt)
[ErrorLog.txt](https://github.com/peted-davis/WeatherFlow_PiConsole/files/10717214/ErrorLog.txt)

**Comment by peted-davis** [comment]
Ah, have you run the curl script at all on the current Raspberry Pi OS build you have your SD card? The curl script installs a bunch of dependencies that are required for the Python command I shared to run successfully. 

If you haven't, run the curl script now. Let it get to the point that it errors (the dependencies will have been installed) and then run the Python command again

**Comment by adamsfour** [comment]
will do stand by

**Comment by adamsfour** [comment]
How long should it run. Been running now for about 10 min. no errors

**Comment by adamsfour** [comment]
I afraid still no luck.  Kivy did finally install. 
Steps I followed
Clean install of OS on SD card
Ran Curl command first
Ran Kivy install 
[ScreendumpKivyInstall.txt](https://github.com/peted-davis/WeatherFlow_PiConsole/files/10717681/ScreendumpKivyInstall.txt)

Ran Curl command again
[ScreenDumpcurl.txt](https://github.com/peted-davis/WeatherFlow_PiConsole/files/10717679/ScreenDumpcurl.txt)

**Comment by adamsfour** [comment]
I was looking at closed cases to see if this had ever happen before. If you look at closed case #61. He had a similar issue. somehow he was able to get it to install. I know ultimately he had other issues but it does appear he was able to get it to work. It appears he using a PI 3 b+ vs me using a PI 3 b. thanks

**Comment by peted-davis** [comment]
Sorry, I made a silly mistake in the Python command I shared. It installed v2.1.0 of Kivy, while the `curl` script tries to install v2.0.0. The `curl` script will try and overwrite the existing version, hence why it failed again. Run this command (it will take a long time to compile again)

`python3 -m pip install https://kivy.org/downloads/2.0.0/Kivy-2.0.0.tar.gz`

and then run the `curl` script for the last time. Hopefully this time it'll work

**Comment by adamsfour** [comment]
no problem. I will give it a shot. I always go back and re-image the SD card first so I know I am starting with a clean build. Will report back once completed

**Comment by peted-davis** [comment]
Ok, make sure you run the `curl` script first before the `python` command on the clean build

**Comment by adamsfour** [comment]
yep

**Comment by peted-davis** [comment]
This is annoying! It looks like I need to bump the version number as something has gone awry with v2.0.0. Can you trying running this command (no need for a clean install):

`python3 -m pip install https://github.com/kivy/kivy/archive/2.1.0.zip`

If that installs we have a solution. Don't try and run the `curl` script afterwards. I will need to bump the version number in the Github repo

**Comment by adamsfour** [comment]
I kick off the script before I had to run out for a few hours. Yesterday I actually had to restart the install as it seem to stall after about two hours

**Comment by adamsfour** [comment]
Also second time I ran it I increased swap space

**Comment by adamsfour** [comment]
Sorry for the delayed responds. Let me know when you have the new script ready and I will give it a shot

 The install worked find for the new version Kivy. Screen dump attached 
[ScreenDumpKivyinstall.txt](https://github.com/peted-davis/WeatherFlow_PiConsole/files/10723559/ScreenDumpKivyinstall.txt)

**Comment by peted-davis** [comment]
OK, I've bumped the version number in the `curl` script. Can you run it and let me know whether everything completes and you're able to start the console

**Comment by adamsfour** [comment]
Will do. Just started script

**Comment by adamsfour** [comment]
Bingo, Up and running perfectly.  Thanks for the help
