### ISSUE TITLE
Will not load Python package

### ISSUE THREAD

**Issue by john0500** [peted-davis/WeatherFlow_PiConsole#90]
I could not preform upgrade due to error. You suggested starting fresh install. I did the steps you outlined and it starts installs and fails at installing cryptographic.

I tried updating pip and came to already meets requirements.
Failed building wheel for cryptography which is needed to install package
     
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'cryptography.hazmat.bindings._rust' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'cryptography.hazmat.bindings._rust' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'cryptography.hazmat.bindings._rust' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      
          =============================DEBUG ASSISTANCE=============================
          If you are seeing a compilation error please try the following steps to
          successfully install cryptography:
          1) Upgrade to the latest pip and try again. This will fix errors for most
             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
          2) Read https://cryptography.io/en/latest/installation/ for specific
             instructions for your platform.
          3) Check our frequently asked questions for more information:
             https://cryptography.io/en/latest/faq/
          4) Ensure you have a recent Rust toolchain installed:
             https://cryptography.io/en/latest/installation/#rust
      
          Python: 3.7.3
          platform: Linux-5.10.63-v7l+-armv7l-with-debian-10.13
          pip: n/a
          setuptools: 67.3.2
          setuptools_rust: 1.5.2
          rustc: n/a
          =============================DEBUG ASSISTANCE=============================
      
      error: can't find Rust compiler
      
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      
      To update pip, run:
      
          pip install --upgrade pip
      
      and then retry package installation.
      
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      
      This package requires Rust >=1.48.0.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects

pi@raspberrypi:~ $ C

**Comment by peted-davis** [comment]
I need to know more information to help fix this. Can you let me know exactly what hardware you are using, and operating system you are running (e.g. Raspberry Pi OS Buster or Bullseye, 32 bit or 64 bit, or something else entirely)

**Comment by john0500** [comment]
Hello, hardware is a Pi 4 Model B, The OS Raspberry, version not known , sorry windows guy. If you can tell me where to look I will. it is 32 Bit

**Comment by peted-davis** [comment]
Ok, thanks for the info. Assuming nothing else is running on that Pi, can you try again with a fresh install of Raspberry Pi OS 32 bit Bullseye (rather than Buster). I think it is Buster that is causing the compatibility issue

**Comment by john0500** [comment]
what's the best way to make sure I get the Bullseye install

**Comment by peted-davis** [comment]
You can either select it when flashing the SD card using the Raspberry Pi Imager, or you can manually download a copy of the OS here: https://www.raspberrypi.com/software/operating-systems/ (it's the first option) and flash it to the SD card manually using the Raspberry Pi Imager. There's some more documentation here: https://www.raspberrypi.com/documentation/computers/getting-started.html#installing-the-operating-system

**Comment by john0500** [comment]
hello, that addressed the issue . I have one small issue. For some reason it did now like my indoor temperature and it come up with a blank reading on indoor temp. Is that easy to fix. Thanks for the help.

**Comment by john0500** [comment]
All back to original and updated. Edited the INI file and good to go.

Thanks again.
