### ISSUE TITLE
Issues installing the update from yesterday 3/3/23

### ISSUE THREAD

**Issue by donaldnaegele** [peted-davis/WeatherFlow_PiConsole#93]
I'm kinda new to the Pi. I only use it for the weather console. It's been working for a year or so with no issues.

I updated the Pi software today and then tried to update WeatherFlow and I'm getting 2 errors. I'm SO lost.

Suggestions?

![IMG_2549](https://user-images.githubusercontent.com/17925461/222916108-e32f676b-7f21-491a-914a-4441dd961e9e.jpg)
![IMG_2550](https://user-images.githubusercontent.com/17925461/222916113-cdee94e4-e0f2-4901-b6aa-fecb17436a12.jpg)

**Describe the bug**

**To Reproduce**

**Screenshots**

**Hardware/OS/Version (please complete the following information):**
 - OS: [e.g. Raspberry Pi OS Bullseye]
 - Hardware: [e.g. Pi3]
 - Console Version: [e.g. 22.3.1]

**Additional context**

**Comment by peted-davis** [comment]
I need to know what version of the Raspberry Pi you are using (3 or 4) and what version of Raspberry Pi OS you are using (Buster or Bullseye). You can find that out by opening a terminal and running `cat /etc/os-release`

**Comment by donaldnaegele** [comment]
Is this what you need? I don't know if I have a 3 or 4. How can I tell? It's in this big case where I can't see any text on it.

Don
![IMG_2551](https://user-images.githubusercontent.com/17925461/222919583-6c4ed06b-6c86-4dd7-b5b4-bc66378904cf.jpg)

**Comment by peted-davis** [comment]
Can you show me the output of `cat /proc/device-tree/model`

**Comment by donaldnaegele** [comment]
I think this is the version.

Don
![IMG_2552](https://user-images.githubusercontent.com/17925461/222920316-a8aa57a5-4a95-401d-986a-7ccd64a8ae59.jpg)

**Comment by peted-davis** [comment]
Yep, got it. 

The problem you're having is that you have a Pi4 but you are running the legacy (Buster) version of Raspberry Pi OS. This use to be a compatible combination, but this update now requires the most recent version of Raspberry Pi OS (Bullseye). I suggest you start with a fresh install of the OS on your SD card and install the console from scratch. This will fix the issues you are seeing

**Comment by donaldnaegele** [comment]
Lots of work. But it’s up and running now. Thank so much for your help. Case closed.
