### ISSUE TITLE
Screen Blanking Not Working in Bullseye

### ISSUE THREAD

**Issue by letizido** [peted-davis/WeatherFlow_PiConsole#96]
Using 32-bit Bullseye on a Pi4B. wfpiconsole installs and runs, but there appears to be a bug in Bullseye that breaks screen blanking on the Pi touchscreen. I installed 32-bit Buster, and screen blanking works properly in the OS. Then, when I tried installing wfpiconsole, I encountered several install failures around the cryptography module. Installer is complaining about not being able to build the wheel for cryptography and needing Rust, and will not complete. So at this point it looks like a choice between wfpiconsole with no screen blanking or screen blanking without wfpiconsole. I also tried xscreensaver but it will only blank the data on the screen. It doesn't turn off the backlight.

**Comment by ctgreybeard** [comment]
I actually turned off screen blanking using raspi-config when I upgraded to bullseye. But I'm not sure if it turned off the backlight. I also seem to recall that there is a boot config option to enable it. I do have that set on my homebridge server and can dig it out if you like. It blanks the text console though, maybe not the graphical one.

**Comment by letizido** [comment]
I resolved this issue by downgrading the xserver-xorg-core package with the below command:

apt install xserver-xorg-core=2:1.20.11-1+deb11u5

There is apparently a bug in the newxserver-xorg-core that breaks screen blanking in Bullseye.
